# Generated by Django 5.2 on 2026-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0022_conselho'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
