# Generated by Django 5.2 on 2026-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0023_utilizador_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
