# Generated by Django 5.2 on 2026-03-20 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automecom', '0024_alter_orcamento_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
